name: Scraping One Piece Characters

on:
  schedule:
    - cron: '0 0 3 * *'  # At 00:00 on day-of-month 3

jobs:
  nakama-scrape:
    runs-on: macOS-latest
    env:
      MONGO_CLOUD_URL: ${{ secrets.MONGO_CLOUD_URL }}
      MONGO_CLOUD_COLLECTION: ${{ secrets.MONGO_CLOUD_COLLECTION }}
      MONGO_CLOUD_DB: ${{ secrets.MONGO_CLOUD_DB }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install janitor package
        run: Rscript -e 'install.packages("janitor", dependencies = TRUE)'
      - name: Install janitor package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'        
      - name: Scrape data from One Piece Fandom Site and Store to MongoDB
        run: Rscript nakama-scrape.R
