name: Daily Tweet

on:
  schedule:
    - cron: '0 15 * * *'  # At 15:00

jobs:
  nakama-tweet:
    runs-on: macOS-latest
    env:
      MONGO_CLOUD_URL: ${{ secrets.MONGO_CLOUD_URL }}
      MONGO_CLOUD_COLLECTION: ${{ secrets.MONGO_CLOUD_COLLECTION }}
      MONGO_CLOUD_DB: ${{ secrets.MONGO_CLOUD_DB }}
      TWITTER_APPS: ${{ secrets.TWITTER_APPS }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript nakama-tweet.R
