name: mention_check

on:
  schedule:
    - cron: '*/15 * * * *'  # check every 15 minutes

jobs:
  publish-data:
    runs-on: macOS-latest
    env:
      ELEPHANT_SQL_DBNAME: ${{ secrets.ELEPHANT_SQL_DBNAME }}
      ELEPHANT_SQL_HOST: ${{ secrets.ELEPHANT_SQL_HOST }}
      ELEPHANT_SQL_USER: ${{ secrets.ELEPHANT_SQL_USER }}
      ELEPHANT_SQL_PASSWORD: ${{ secrets.ELEPHANT_SQL_PASSWORD }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install RPostgreSQL package
        run: Rscript -e 'install.packages("RPostgreSQL", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript prayers-reply.R
